
systemLog:
  destination: file
  path: "./mongo-system.log"
  logAppend: true

storage: 
  dbPath: "./mongodb"
  journal:
    enabled: true

processManagement: 
  fork: true

net:
  bindIp: 127.0.0.1
  port: 27717
  ssl:
    mode: requireSSL
    PEMKeyFile: "mongoserver-key-crt.pem"
    CAFile: "../enterprise_mongo_ca/pki/ca.crt" 

security:
  authorization: enabled
  enableEncryption: true
  kmip:
    serverName: kmipserver
    port: 5696
    serverCAFile: "/home/fiona/wd/dwp/cis/mongo_enterprise_ssl/enterprise_mongo_ca/pki/ca.crt"
    clientCertificateFile: "/home/fiona/wd/dwp/cis/mongo_enterprise_ssl/enterprise_mongo_config/kmipclient-key-and-cert.pem" 
    keyIdentifier: "2"

  